version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-8
    ports:
      - 3306:3306
    networks:
      - mysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./dbdata:/var/lib/mysql

networks:
  mysql-net:
    external: true

