version: '3'
services:
  postgresql:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-net
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data:
    driver: local
networks:
  postgres-net:
    driver: 'bridge'
